### ISSUE TITLE
Proposal: Support non-delegate version

### ISSUE THREAD

**Issue by charlierudolph** [Originate/end_state#29]
I think it would be nice if you could use this without being a delegate.

```ruby
object = MyMachine.decorate(object)
machine = MyMachine.new(object)
```

The decorator works as a delegator adding the machines methods (through method missing). 
And the initializer simply returns the machine.

**Comment by alexpeachey** [comment]
What would be the benefit of not delegating?

**Comment by charlierudolph** [comment]
Allows you to use a standalone state machine. I would imagine it making testing simpler and would allow it to be used in more places. I'll close if you don't agree.

**Comment by alexpeachey** [comment]
So all the machine needs to function is an object that has an attribute `state` (changable using the `state_attribute` macro).

So if you just wanted a "standalone state machine" then just hand it something that it wants:

`machine = MyMachine.new(OpenStruct.new(state: :idle))`

Then you can use the machine all you want.

Or am I missing something else about this issue?

**Comment by charlierudolph** [comment]
Closing as the guard / actions / concluders all get passed the delegated object so this wouldn't make sense.
